services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # COMMANDS
    #

    # auto-register all commands as services
    Pimcore\Bundle\BundleGeneratorBundle\Command\:
        resource: '../../Command'
        exclude: '../../Command/Validators.php'
        tags: ['console.command']

    Pimcore\Bundle\BundleGeneratorBundle\Command\GenerateBundleCommand:
        public: true

    Pimcore\Bundle\BundleGeneratorBundle\Command\Helper\QuestionHelper:
        public: true
